production_url: 'http://nathan.stitt.org'

core:
  summary_lines: 1
  sort: ["date", "desc"]
  layout: "core"

widgets:
    analytics:
      use: google
      tracking_id: 'UA-44612247-4'

asset_pipeline:
  enable: true

posts:
  sort: ["date", "desc"]

images:
  use: static